sentences = [
    "Hey! How's your day going? ^o^",
    "Hey there, sunshine! ^^",
    "How's your day sparkling? ✨",
    "Sending you smiles for miles! 😊",
    "What's making you grin today? :D",
    "Good morning, sleepyhead! 😴",
    "Have you hugged a teddy bear today? 🧸",
    "Hi, sweet pea! 🌸",
    "What's the happiest thought on your mind? 💭",
    "Hey cutie, ready to conquer the day? UnU",
    "Are you ready to sprinkle some kindness? ^o^",
    "Hello, rainbow! 🌈",
    "Sending you a bouquet of happiness! 💐",
    "How's your heart singing today? 🎶",
    "Hey there, little star! ⭐️",
    "What's your favorite flavor of happiness? 🍭",
    "Good day, lovely soul! 💖",
    "Have you found your daily dose of magic? ✨",
    "Hi there, precious gem! 💎",
    "What's the sweetest thing you've seen today? 🍬",
    "Hello, sunshine! ☀️",
    "Sending you a pocketful of sunshine! ☀️",
    "How's your heart dancing today? 💃",
    "Hey, darling! 💕",
    "Are you ready to twinkle like a star? ✨",
    "Good morning, lovely! 🌼",
    "Have you hugged a fluffy cloud today? ☁️",
    "Hi, honey bun! 🍯",
    "What's bringing a twinkle to your eyes? ✨",
    "Hey there, cupcake! 🧁",
    "Are you ready to spread some love? ❤️",
    "Hello, sweetie pie! 🥧",
    "Sending you a sprinkle of fairy dust! ✨",
    "How's your day blooming? 🌷",
    "Hi, sugarplum! 🍬",
    "What's making your heart skip a beat? 💓",
    "Hey, angel face! 😇",
    "Are you ready to dance with joy? 💃",
    "Good morning, buttercup! 🌼",
    "Have you made a wish on a dandelion today? 🌼",
    "Hi there, sunshine! ☀️",
    "What's the happiest sound you've heard today? 🎶",
    "Hello, little ray of light! ☀️",
    "Sending you a basket of smiles! 😊",
    "How's your day painting the world with joy? 🎨",
    "Hey, sweet cheeks! 🍑",
    "Are you ready to giggle like a giggly jellybean? xD",
    "Good morning, dear heart! 💖",
    "Have you whispered a secret to a butterfly today? 🦋",
    "Hi, cuddle bug! 🐞",
    "What's making your heart feel fuzzy today?"
]